## Class(day-34:2-7-20)
## Document link:- http://tiny.cc/02-07-2020

## Importing Libraries:

In [1]:
import pandas as pd
import numpy as np

## Reading the data:

In [4]:
data = pd.read_csv("https://raw.githubusercontent.com/Mounika-Kajjam/Datasets/master/spam.csv",encoding='latin-1')
data.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [5]:
data.shape

(5572, 5)

In [16]:
# Drop the unnecessary columns
data.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'],axis=1, inplace=True)
data.shape

(5572, 2)

## splitting the data:

In [7]:
# split the data
# 80% of the data will be in training data  20% of the data will be in testing
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(data.v2,data.v1,test_size = 0.2)

In [8]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(4457,)
(4457,)
(1115,)
(1115,)

## initialising count vectorizer

In [9]:
# count vectorizer
from sklearn.feature_extraction.text import CountVectorizer

# creating an object for countvectorizer
count_vect = CountVectorizer()

## To get the feature names:

In [10]:
# generate the word counts for the words in the documents
word_count_vector = count_vect.fit(x_train)

# to get the feature names
word_count_vector.get_feature_names()

['00',
 '000',
 '000pes',
 '008704050406',
 '0089',
 '0121',
 '01223585236',
 '01223585334',
 '0125698789',
 '02',
 '0207',
 '02072069400',
 '02073162414',
 '02085076972',
 '021',
 '03',
 '04',
 '0430',
 '05',
 '050703',
 '0578',
 '06',
 '07',
 '07008009200',
 '07090201529',
 '07090298926',
 '07099833605',
 '07123456789',
 '0721072',
 '07732584351',
 '07734396839',
 '07742676969',
 '0776xxxxxxx',
 '07781482378',
 '07786200117',
 '077xxx',
 '078',
 '07801543489',
 '07808247860',
 '07808726822',
 '07815296484',
 '07821230901',
 '078498',
 '07880867867',
 '0789xxxxxxx',
 '07946746291',
 '0796xxxxxx',
 '07973788240',
 '07xxxxxxxxx',
 '08',
 '0800',
 '08000407165',
 '08000776320',
 '08000839402',
 '08000930705',
 '08000938767',
 '08001950382',
 '08002888812',
 '08002986030',
 '08002986906',
 '08002988890',
 '0808',
 '08081263000',
 '08081560665',
 '0825',
 '083',
 '0844',
 '0845',
 '08450542832',
 '08452810071',
 '08452810073',
 '08452810075over18',
 '0870',
 '08700435505150p',
 '08700469649',
 '08700621170150p',
 '08701237397',
 '08701417012',
 '08701417012150p',
 '0870141701216',
 '087016248',
 '08701752560',
 '087018728737',
 '0870241182716',
 '08702490080',
 '08702840625',
 '08704050406',
 '08704439680',
 '08704439680ts',
 '08706091795',
 '0870737910216yrs',
 '08707500020',
 '08707509020',
 '0870753331018',
 '08707808226',
 '08708034412',
 '08708800282',
 '08709222922',
 '08709501522',
 '0871',
 '087104711148',
 '08712101358',
 '08712103738',
 '0871212025016',
 '08712300220',
 '08712317606',
 '08712400200',
 '08712400602450p',
 '08712400603',
 '08712402050',
 '08712402578',
 '08712402779',
 '08712402902',
 '08712405020',
 '08712405022',
 '08712460324',
 '08712466669',
 '0871277810710p',
 '0871277810810',
 '08714342399',
 '08714712379',
 '08714712388',
 '08714712394',
 '08714712412',
 '08714714011',
 '08715203028',
 '08715203649',
 '08715203652',
 '08715203656',
 '08715203685',
 '08715203694',
 '08715205273',
 '08715705022',
 '08717111821',
 '08717168528',
 '08717205546',
 '0871750',
 '08717507382',
 '08717509990',
 '08717890890Ã¥',
 '08717898035',
 '08718711108',
 '08718720201',
 '08718723815',
 '08718725756',
 '08718726270',
 '087187262701',
 '08718726970',
 '08718726971',
 '08718726978',
 '087187272008',
 '08718727868',
 '08718727870',
 '08718730555',
 '08718730666',
 '08718738001',
 '08718738002',
 '08719180219',
 '08719180248',
 '08719181259',
 '08719181503',
 '08719181513',
 '08719839835',
 '08719899229',
 '08719899230',
 '09',
 '09041940223',
 '09050000332',
 '09050000460',
 '09050000555',
 '09050000878',
 '09050001295',
 '09050001808',
 '09050002311',
 '09050003091',
 '09050090044',
 '09050280520',
 '09053750005',
 '09056242159',
 '09057039994',
 '09058091854',
 '09058091870',
 '09058094455',
 '09058094507',
 '09058094565',
 '09058094594',
 '09058094597',
 '09058094599',
 '09058095107',
 '09058095201',
 '09058097189',
 '09058097218',
 '09058098002',
 '09058099801',
 '09061104276',
 '09061209465',
 '09061213237',
 '09061221061',
 '09061221066',
 '09061701444',
 '09061701461',
 '09061701939',
 '09061702893',
 '09061743386',
 '09061743806',
 '09061743810',
 '09061743811',
 '09061744553',
 '09061749602',
 '09061790121',
 '09061790125',
 '09061790126',
 '09063440451',
 '09063442151',
 '09063458130',
 '0906346330',
 '09064011000',
 '09064012103',
 '09064012160',
 '09064015307',
 '09064017295',
 '09064017305',
 '09064018838',
 '09064019014',
 '09064019788',
 '09065069120',
 '09065069154',
 '09065171142',
 '09065174042',
 '09065394514',
 '09065394973',
 '09065989180',
 '09065989182',
 '09066350750',
 '09066358152',
 '09066358361',
 '09066361921',
 '09066362206',
 '09066362220',
 '09066362231',
 '09066364311',
 '09066364349',
 '09066364589',
 '09066368327',
 '09066368470',
 '09066368753',
 '09066380611',
 '09066382422',
 '09066612661',
 '09066649731from',
 '09066660100',
 '09071512433',
 '09071517866',
 '09090900040',
 '09094100151',
 '09094646899',
 '09095350301',
 '09099725823',
 '09099726395',
 '09099726429',
 '09099726481',
 '09111030116',
 '09111032124',
 '09701213186',
 '0a',
 '10',
 '100',
 '1000',
 '1000s',
 '100percent',
 '100txt',
 '1013',
 '1030',
 '10am',
 '10k',
 '10p',
 '10ppm',
 '10th',
 '11',
 '1120',
 '113',
 '114',
 '116',
 '1172',
 '118p',
 '11mths',
 '11pm',
 '12',
 '1205',
 '120p',
 '121',
 '1225',
 '123',
 '125',
 '1250',
 '125gift',
 '128',
 '12hrs',
 '12mths',
 '13',
 '130',
 '1327',
 '139',
 '14',
 '140',
 '1405',
 '140ppm',
 '145',
 '1450',
 '146tf150p',
 '14tcr',
 '14thmarch',
 '15',
 '150',
 '1500',
 '150p',
 '150p16',
 '150pm',
 '150ppermesssubscription',
 '150ppm',
 '150ppmpobox10183bhamb64xe',
 '150pw',
 '151',
 '153',
 '15541',
 '16',
 '165',
 '1680',
 '169',
 '177',
 '18',
 '180',
 '1843',
 '18p',
 '18yrs',
 '1956669',
 '1apple',
 '1b6a5ecef91ff9',
 '1cup',
 '1er',
 '1hr',
 '1im',
 '1lemon',
 '1mega',
 '1million',
 '1pm',
 '1st',
 '1st4terms',
 '1stchoice',
 '1stone',
 '1thing',
 '1tulsi',
 '1win150ppmx3',
 '1winaweek',
 '1winawk',
 '1x150p',
 '1yf',
 '20',
 '200',
 '2000',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '200p',
 '2025050',
 '20p',
 '21',
 '21870000',
 '21st',
 '22',
 '220',
 '220cm2',
 '2309',
 '23f',
 '23g',
 '24',
 '24hrs',
 '24th',
 '25',
 '250',
 '250k',
 '255',
 '25p',
 '26',
 '2667',
 '26th',
 '27',
 '28',
 '2814032',
 '28days',
 '28th',
 '28thfeb',
 '29',
 '2b',
 '2bold',
 '2c',
 '2channel',
 '2day',
 '2end',
 '2exit',
 '2ez',
 '2find',
 '2getha',
 '2geva',
 '2go',
 '2gthr',
 '2kbsubject',
 '2lands',
 '2marrow',
 '2moro',
 '2morow',
 '2morro',
 '2morrow',
 '2mrw',
 '2nd',
 '2nights',
 '2nite',
 '2optout',
 '2price',
 '2rcv',
 '2stop',
 '2stoptx',
 '2stoptxt',
 '2u',
 '2u2',
 '2waxsto',
 '2wks',
 '2wt',
 '2wu',
 '2yr',
 '2yrs',
 '30',
 '300',
 '3000',
 '300603',
 '300p',
 '3030',
 '30apr',
 '30ish',
 '30pm',
 '30pp',
 '31',
 '3100',
 '310303',
 '31p',
 '32000',
 '3230',
 '32323',
 '326',
 '33',
 '330',
 '350',
 '3510i',
 '35p',
 '3650',
 '36504',
 '3680',
 '373',
 '3750',
 '37819',
 '38',
 '391784',
 '3aj',
 '3d',
 '3days',
 '3g',
 '3gbp',
 '3hrs',
 '3lions',
 '3lp',
 '3miles',
 '3mins',
 '3mobile',
 '3optical',
 '3qxj9',
 '3rd',
 '3ss',
 '3uz',
 '3wks',
 '3xx',
 '3xÃ¥',
 '40',
 '400',
 '400mins',
 '400thousad',
 '402',
 '4041',
 '40411',
 '40533',
 '40gb',
 '40mph',
 '41685',
 '41782',
 '420',
 '42049',
 '4217',
 '42810',
 '430',
 '434',
 '44',
 '440',
 '4403ldnw1a7rw18',
 '447797706009',
 '447801259231',
 '449071512431',
 '45',
 '450',
 '450p',
 '450pw',
 '45239',
 '45pm',
 '47',
 '4719',
 '4742',
 '47per',
 '48',
 '4882',
 '48922',
 '49',
 '49557',
 '4a',
 '4d',
 '4eva',
 '4few',
 '4fil',
 '4get',
 '4give',
 '4goten',
 '4info',
 '4mths',
 '4qf2',
 '4t',
 '4th',
 '4the',
 '4thnov',
 '4txt',
 '4u',
 '4utxt',
 '4wrd',
 '4xx26',
 '4years',
 '50',
 '500',
 '5000',
 '505060',
 '50award',
 '50ea',
 '50gbp',
 '50p',
 '50perweeksub',
 '50perwksub',
 '50pmmorefrommobile2bremoved',
 '50rcvd',
 '50s',
 '515',
 '523',
 '526',
 '528',
 '530',
 '54',
 '542',
 '5digital',
 '5free',
 '5ish',
 '5k',
 '5min',
 '5mls',
 '5p',
 '5pm',
 '5th',
 '5wb',
 '5we',
 '5wq',
 '5years',
 '60',
 '600',
 '6031',
 '6089',
 '60p',
 '61610',
 '62220cncl',
 '6230',
 '62468',
 '62735',
 '630',
 '63miles',
 '645',
 '674',
 '69101',
 '69200',
 '69669',
 '69696',
 '69698',
 '69855',
 '69866',
 '69876',
 '69888',
 '69911',
 '69969',
 '69988',
 '6days',
 '6hl',
 '6hrs',
 '6ish',
 '6missed',
 '6months',
 '6pm',
 '6th',
 '6times',
 '6wu',
 '6zf',
 '700',
 '71',
 '7250',
 '7250i',
 '730',
 '731',
 '74355',
 '75',
 '750',
 '7548',
 '75max',
 '762',
 '7634',
 '7684',
 '77',
 '7732584351',
 '78',
 '786',
 '7876150ppm',
 '79',
 '7am',
 '7cfca1a',
 '7ish',
 '7mp',
 '7oz',
 '7pm',
 '7th',
 '7ws',
 '7zs',
 '80',
 '800',
 '8000930705',
 '80062',
 '8007',
 '80082',
 '80086',
 '80122300p',
 '80160',
 '80182',
 '8027',
 '80488',
 '80608',
 '8077',
 '80878',
 '81010',
 '81151',
 '81303',
 '81618',
 '82050',
 '820554ad0a1705572711',
 '82242',
 '82277',
 '82324',
 '82468',
 '83021',
 '83039',
 '83049',
 '83110',
 '83118',
 '83222',
 '83332',
 '83355',
 '83370',
 '83383',
 '83600',
 '83738',
 '84025',
 '84122',
 '84128',
 '84199',
 '84484',
 '85',
 '85023',
 '85069',
 '85233',
 '8552',
 '85555',
 '86021',
 '861',
 '864233',
 '86688',
 '86888',
 '87021',
 '87066',
 '87070',
 '87077',
 '87121',
 '87131',
 '8714714',
 '872',
 '87239',
 '87575',
 '8800',
 '88039',
 '88066',
 '88088',
 '88222',
 '88600',
 '88800',
 '8883',
 '88877',
 '88888',
 '89034',
 '89070',
 '89080',
 '89123',
 '89545',
 '89555',
 '89693',
 '89938',
 '8am',
 '8lb',
 '8p',
 '8pm',
 '8th',
 '8wp',
 '900',
 '9061100010',
 '9153',
 '9280114',
 '930',
 '9307622',
 '946',
 '9755',
 '9758',
 '97n7qp',
 '98321561',
 '99',
 '9996',
 '9ae',
 '9am',
 '9ja',
 '9pm',
 '9t',
 '9th',
 '9yt',
 '____',
 'a21',
 'a30',
 'aa',
 'aah',
 'aaooooright',
 'aathi',
 'ab',
 'abdomen',
 'abeg',
 'aberdeen',
 'abi',
 'ability',
 'abiola',
 'abj',
 'able',
 'abnormally',
 'about',
 'aboutas',
 'above',
 'abroad',
 'absolutely',
 'absolutly',
 'abstract',
 'abt',
 'abta',
 'aburo',
 'abuse',
 'ac',
 'academic',
 'acc',
 'accent',
 'accept',
 'access',
 'accessible',
 'accident',
 'accidentally',
 'accommodation',
 'accommodationvouchers',
 'accordin',
 'accordingly',
 'account',
 'accounting',
 'accounts',
 'accumulation',
 'ache',
 'acid',
 'acknowledgement',
 'acl03530150pm',
 'acnt',
 'aco',
 'across',
 'act',
 'acted',
 'actin',
 'acting',
 'action',
 'activate',
 'active',
 'activities',
 'actor',
 'actual',
 'actually',
 'ad',
 'adam',
 'add',
 'addamsfa',
 'added',
 'addicted',
 'addie',
 'adding',
 'address',
 'adds',
 'adewale',
 'adi',
 'adjustable',
 'admin',
 'administrator',
 'admirer',
 'admit',
 'adore',
 'adoring',
 'adp',
 'adrian',
 'ads',
 'adult',
 'adults',
 'advance',
 'adventure',
 'advice',
 'advise',
 'advisors',
 'aeronautics',
 'aeroplane',
 'afew',
 'affair',
 'affairs',
 'affection',
 'affectionate',
 'affections',
 'affidavit',
 'afford',
 'afraid',
 'african',
 'aft',
 'after',
 'afternon',
 'afternoon',
 'afternoons',
 'afterwards',
 'aftr',
 'ag',
 'again',
 'against',
 'agalla',
 'age',
 'age16',
 'age23',
 'agency',
 'agent',
 'agents',
 'ages',
 'agidhane',
 'aging',
 'ago',
 'agree',
 'ah',
 'aha',
 'ahead',
 'ahhh',
 'ahhhh',
 'ahmad',
 'ahold',
 'aid',
 'aids',
 'aig',
 'aight',
 'ain',
 'aint',
 'air',
 'airport',
 'airtel',
 'aiya',
 'aiyah',
 'aiyar',
 'aiyo',
 'ajith',
 'ak',
 'aka',
 'akon',
 'al',
 'alaikkum',
 'alaipayuthe',
 'albi',
 'album',
 'alcohol',
 'aldrine',
 'alert',
 'alertfrom',
 'alerts',
 'aletter',
 'alex',
 'alfie',
 'algarve',
 'algorithms',
 'ali',
 'alian',
 'alibi',
 'alive',
 'all',
 'allah',
 'allalo',
 'allday',
 'alle',
 'allo',
 'allow',
 'allowed',
 'allows',
 'almost',
 'alone',
 'along',
 'alot',
 'already',
 'alright',
 'alrite',
 'also',
 'alter',
 'alternative',
 'although',
 'aluable',
 'alwa',
 'always',
 'alwys',
 'am',
 'amanda',
 'amazing',
 'ambrith',
 'american',
 'ami',
 'amigos',
 'amk',
 'ammae',
 'ammo',
 'among',
 'amongst',
 'amore',
 'amount',
 'amp',
 'amrca',
 'amrita',
 'ams',
 'amt',
 'amused',
 'amy',
 'an',
 'ana',
 'anal',
 'anand',
 'and',
 'anderson',
 'andre',
 'andres',
 'andrews',
 'andros',
 'angels',
 'angry',
 'animal',
 'animation',
 'anjie',
 'anna',
 'annie',
 'anniversary',
 'announced',
 'announcement',
 'annoyin',
 'annoying',
 'anonymous',
 'anot',
 'another',
 'ans',
 'ansr',
 'answer',
 'answered',
 'answering',
 'answers',
 'answr',
 'antha',
 'anthony',
 'anti',
 'antibiotic',
 'any',
 ...]

## Transforming the data:

In [11]:
doc_array = word_count_vector.transform(x_train)
doc_array

<4457x7744 sparse matrix of type '<class 'numpy.int64'>'
	with 59547 stored elements in Compressed Sparse Row format>

In [12]:
# converting to a array
doc_array = word_count_vector.transform(x_train).toarray()
doc_array

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

## Specifying column names

In [13]:
# converting the array into a dataframe
pd.DataFrame(doc_array)

,0,1,2,3,4,5,6,7,8,9,...,7734,7735,7736,7737,7738,7739,7740,7741,7742,7743
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4452,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4453,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4454,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4455,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4456,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
feature_matrix = pd.DataFrame(doc_array,columns= word_count_vector.get_feature_names())
feature_matrix

,00,000,000pes,008704050406,0089,0121,01223585236,01223585334,0125698789,02,...,Ã¬Â¼1,Ã¬Ã¤,Ã¬Ã¯,Ã»_,Ã»_thanks,Ã»Âªm,Ã»Âªt,Ã»Âªve,Ã»Ã¯harry,Ã»Ã²
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4452,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4453,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4454,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4455,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4456,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
# pd.set_option('display.max_rows',None)